---
- name: Create gateway subnet
  hosts: localhost
  tasks:
   - name: Create new Gateway Subnet
     azure_rm_subnet:
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnet_name }}"
      name: "GatewaySubnet"
      address_prefix_cidr: "192.168.1.224/27"
     register: subnet_info
     
   - name: Print subnet info
     debug:
      var: subnet_info            
