---
- name: Create a new route table and entry for customer VtV connection and assign to the subnet
  hosts: localhost
  tasks:
   - name: Create new route table
     azure_rm_routetable:
       name: "{{ rtb_name }}"
       resource_group: "{{ rg_name }}"
       tags:
        CreatedBy: "{{ tower_user_name }}"
        Customer: "{{ customer_name }}"
        CostCenter: "{{ CC }}" 
     register: rtb_info
     
   - name: Print rtb info
     debug:
      var: rtb_info
      
   - name: Create new route entry
     azure_rm_route:
      name: VNFM_management_subnet
      resource_group: "{{ rg_name }}"
      route_table_name: "{{ rtb_name }}"
      address_prefix: "{{ vnfm_mgmt_snet }}"
      next_hop_type: virtual_network_gateway 
      tags:
       CreatedBy: "{{ tower_user_name }}"
       Customer: "{{ customer_name }}"
       CostCenter: "{{ CC }}" 
     register: route_entry
     
   - name: Print route entry
      debug:
       var: route_entry
       
   - name: Associate the route table to the customer subnet
     azure_rm_subnet:
      virtual_network_name: "{{ vnet_name }}"
      name: "{{ subnet1_name }}"
      resource_group: "{{ rg_name }}"
      route_table: "{{ rtb_name }}"
      tags:
       CreatedBy: "{{ tower_user_name }}"
       Customer: "{{ customer_name }}"
       CostCenter: "{{ CC }}" 
     register: subnet_ass
       
   - name: Print association result
     debug:
      var: subnet_ass
       
