---
- name: Create vnet-to-vnet connection
  hosts: localhost
  tasks:
   - name: Create new public IP for Azure Gateway
     azure_rm_publicipaddress:
       allocation_method: static
       name: dev-az-ew-customer01-pip
       resource_group: test
       sku: basic
     register: pip_address
     
   -name: Print pip info
    debug:
     msg: "{{ pip_address.state.ip_address }}"
     msg: "{{ pip_address.state.name }}"
            
   - name: Create new gateway  
     azure_rm_virtualnetworkgateway:
      resource_group: test
      name: dev-azew-customer01-gw
      ip_configurations:
        - name: testipconfig
          private_ip_allocation_method: Dynamic
          public_ip_address_name: "{{ pip_address.state.name }}"
      virtual_network: test_vnet
     register: vnet_info
  
   - name: Print VNet info
     debug:
      var: vnet_info


