---
- name: Create VPN gateway with PIP, VNET, GWSUBNET
  hosts: localhost
  tasks:
   - name: Create new public IP for Azure Gateway
     azure_rm_publicipaddress:
      allocation_method: dynamic
      name: "{{ pip_name }}"
      resource_group: "{{ rg_name }}"
      sku: basic
      tags:
       CreatedBy: "{{ tower_user_name }}"
       Customer: "{{ customer_name }}"
       CostCenter: "{{ CC }}"
      register: pip_address
     
   - name: Print pip info
     debug:
      msg: "{{ pip_address.state.name }}"
   
   - name: Create the new vnet
     azure_rm_virtualnetwork:
      name: "{{ vnet_name }}"
      resource_group: "{{ rg_name }}"
      address_prefixes_cidr: 
       - "{{ vnet_addressspace }}"
       - "{{ vnet_addressspace2 }}"
      tags:
       CreatedBy: "{{ tower_user_name }}"
       Customer: "{{ customer_name }}"
       CostCenter: "{{ CC }}"
      register: vnet_info
   
   - name: Create new Subnet
     azure_rm_subnet:
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnet_name }}"
      name: "{{ vnet_subnet_name }}"
      address_prefix_cidr: "{{ subnet_iprange }}"
     register: subnet_info
     
   - name: Create new Gateway Subnet
     azure_rm_subnet:
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnet_name }}"
      name: "GatewaySubnet"
      address_prefix_cidr: "{{ gwsnet_iprange }}"
     register: subnet_info
     
   - name: Print subnet info
     debug:
      var: subnet_info                     
   
   - name: Create new gateway  
     azure_rm_virtualnetworkgateway:
      resource_group: "{{ rg_name }}"
      name: "{{ gw_name }}"
      ip_configurations:
        - name: testipconfig
          private_ip_allocation_method: Dynamic
          public_ip_address_name: "{{ pip_address.state.name }}"
          subnet: "{{ subnet_name }}"
      virtual_network: "{{ vnet_name }}"
      tags:
       CreatedBy: "{{ tower_user_name }}"
       Customer: "{{ customer_name }}"
       CostCenter: "{{ CC }}"register: vnet_info
  
   - name: Print VNet info
     debug:
      var: vnet_info
