---
- name: Create vnet-to-vnet connection
  hosts: localhost
  tasks:
   - name: Create new public IP for Azure Gateway
     azure_rm_publicipaddress:
       allocation_method: dynamic
       name: dev-az-ew-customer01-pip
       resource_group: "{{ rg_name }}"
       sku: basic
     register: pip_address
     
   - name: Print pip info
     debug:
      msg: "{{ pip_address.state.name }}"
   
   - name: Create the new vnet
     azure_rm_virtualnetwork:
      name: "{{ vnet_name }}"
      resource_group: "{{ rg_name }}"
      address_prefixes_cidr: 
       - "192.168.1.0/24"
     register: vnet_info
   
   - name: Create new Gateway Subnet
     azure_rm_subnet:
      resource_group: "{{ rg_name }}"
      virtual_network_name: "{{ vnet_name }}"
      name: "GatewaySubnet"
      address_prefix_cidr: "192.168.1.224/27"
     register: subnet_info
     
   - name: Print subnet info
     debug:
      var: subnet_info                     
   
   - name: Create new gateway  
     azure_rm_virtualnetworkgateway:
      resource_group: "{{ rg_name }}"
      name: dev-az-ew-customer01-gw
      ip_configurations:
        - name: testipconfig
          private_ip_allocation_method: Dynamic
          public_ip_address_name: "{{ pip_address.state.name }}"
          subnet: "{{ subnet_name }}"
      virtual_network: "{{ vnet_name }}"
     register: vnet_info
  
   - name: Print VNet info
     debug:
      var: vnet_info
