---
- name: Create vnet-to-vnet connection
  hosts: localhost
  tasks:
   - name: Create new local network gateway
     azure_rm_resource:
      subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
      client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
      secret: "{{ lookup('env', 'AZURE_SECRET') }}"
      resource_group: "{{ rg_name }}"
      resource_type: "localNetworkGateways"
      provider: "Network"
      resource_name: "{{ lgw_name }}"
      body:
       location: "{{ region }}"
       apiVersion: "2020-05-01"
       properties:
        localNetworkAddressSpace:
         addressPrefixes:
          - "192.168.1.0/24"
       tags:
        CreatedBy: "{{ tower_user_name }}"
        Customer: "{{ customer_name }}"
        CostCenter: "{{ CC }}" 
     register: local_gateway

   - name: LGW info
     debug:
      msg: "{{ local_gateway }}"
