---
- name: Create new vnet_to_vnet connection
  azure_rm_resource:
   subscription_id: "{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}"
   client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
   tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
   secret: "{{ lookup('env', 'AZURE_SECRET') }}"
   resource_group: "{{ rg_name }}"
   resource_type: "connections"
   provider: "Network"
   resource_name: "{{ vtv_name }}"
   body:
    location: "{{ region }}"
#    apiVersion: "2020-05-01"
    properties:
     connectionType: 1
     connectionProtocol: 0 
     sharedKey: "vnmf12345"
     virtualNetworkGateway1:
      id: "/subscriptions/f08e6091-2405-43e0-86be-9bd1f7e13a46/resourceGroups/vnfm_management_rg/providers/Microsoft.Network/virtualNetworkGateways/management_zone-gateway"
     virtualNetworkGateway2:
      id: "/subscriptions/389e78a9-234f-4268-be07-4a14e581ccd4/resourceGroups/test/providers/Microsoft.Network/virtualNetworkGateways/dev-az-ew-cust01gw01-gw" 
    tags:
     CreatedBy: "{{ tower_user_name }}"
     Customer: "{{ customer_name }}"
     CostCenter: "{{ CC }}" 
  register: vnet_to_vnet

- name: vtv info
  debug:
   msg: "{{ vnet_to_vnet }}"
